version: "3"
services:
  app:
    build: ./app
    depends_on:
      - db
    ports:
      - "8090:8080"
    links:
      - db


  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./bd_init:/docker-entrypoint-initdb.d/:ro
    ports:
      - "4200:3306"
