version: "3"
services:
  app:
    build: ./foodcart_app 
    ports:
      - "8080:5000"
    links:
      - db 

  db:
    image: mysql:8.0 
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./db_init:/docker-entrypoint-intidb.d/:ro
    ports:
      - "4200:3306"